_target_: src.models.fb_module.FBModule

net:
  _target_: src.models.components.classifier_net.ClassifierNet
  bert:
    _target_: src.models.components.backbone.bert.Bert
    model_dir: ${paths.model_dir}
    aggregator_names: ['bert_pooler', 'avg_pooler']
  classifier:
    _target_: src.models.components.backbone.classifier.MultSampleClassifier
    input_dim: 768
    num_class: ${datamodule.num_class}
    dropout_rate: 0.2
    dropout_num: 4

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 2e-5
  eps: 1e-6
  weight_decay: 0.0

scheduler:
  _target_: transformers.get_cosine_schedule_with_warmup
  _partial_: true
  num_warmup_steps: 0
  num_cycles: 0.5