defaults:
  - kfold_model_checkpoint.yaml
  - model_summary.yaml
  - rich_progress_bar.yaml
  - _self_


early_stopping:
  monitor: "val/loss"
  patience: 3
  mode: "min"

model_summary:
  max_depth: -1
